"""fix: foreign key to application id

Revision ID: 5bfaea6ac659
Revises: ac8fd17f57f8
Create Date: 2025-06-06 03:50:54.430438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bfaea6ac659'
down_revision: Union[str, None] = 'ac8fd17f57f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('application_id', sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'analyses', 'applications', ['application_id'], ['application_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.drop_column('analyses', 'application_id')
    # ### end Alembic commands ###
