"""fix: change application_id to varchar

Revision ID: ac8fd17f57f8
Revises: c8086cae6900
Create Date: 2025-06-06 03:48:39.694009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac8fd17f57f8'
down_revision: Union[str, None] = 'c8086cae6900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('analyses_application_id_fkey'), 'analyses', type_='foreignkey')
    op.drop_column('analyses', 'application_id')
    op.alter_column('applications', 'application_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'application_id',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('analyses', sa.Column('application_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('analyses_application_id_fkey'), 'analyses', 'applications', ['application_id'], ['application_id'])
    # ### end Alembic commands ###
