"""create table analysis

Revision ID: d84869911bc6
Revises: 84ee5a01f0f7
Create Date: 2025-06-05 05:56:47.135324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd84869911bc6'
down_revision: Union[str, None] = '84ee5a01f0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('negative_wordclouds', sa.String(length=255), nullable=True),
    sa.Column('positive_wordclouds', sa.String(length=255), nullable=True),
    sa.Column('neutral_wordclouds', sa.String(length=255), nullable=True),
    sa.Column('bug_wordclouds', sa.String(length=255), nullable=True),
    sa.Column('feature_wordclouds', sa.String(length=255), nullable=True),
    sa.Column('ux_wordclouds', sa.String(length=255), nullable=True),
    sa.Column('noise_wordclouds', sa.String(length=255), nullable=True),
    sa.Column('positive_count', sa.Integer(), nullable=False),
    sa.Column('negative_count', sa.Integer(), nullable=False),
    sa.Column('neutral_count', sa.Integer(), nullable=False),
    sa.Column('bug_count', sa.Integer(), nullable=False),
    sa.Column('feature_count', sa.Integer(), nullable=False),
    sa.Column('ux_count', sa.Integer(), nullable=False),
    sa.Column('noise_count', sa.Integer(), nullable=False),
    sa.Column('last_analysis_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('confidence_score_sentiment', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('confidence_score_category', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PROCESSING', 'COMPLETED', name='analysis_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('applications', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_table('analyses')
    # ### end Alembic commands ###
